### ISSUE TITLE
String could not be parsed

### ISSUE THREAD

**Issue by ghost** [sardoj/VTModuleDesigner#10]
Hello!
Thanks for this plugin! A wonderful work what you have done. But till now I got one problem: When I try to load the existant module "contacts" I got : "String could not be parsed as XML" .

Iam using the german language. Could that be a problem ?

**Comment by ghost** [comment]
hi!
I dont get it to work. I can load almost every module except Persons (contacts). Is there any possbility to add another related list to this person module?

**Comment by sardoj** [comment]
Hi!

Is it possible that you're Contact module's manifest.xml is corrupted.
Maybe because there is & somewhere instead of &amp; or for other reasons.

To try to export it directly from Settings panel, go before into your
database (vtiger_tab) and for the Contact module, set "customized" value to
1 (instead of 0).

Once your module exported, unzip it and look into "manifest.xml" file.

Regards,

Jonathan SARDO
[image: Images intégrées 5]
Tél. 06 99 45 50 47

2014-03-03 12:14 GMT+01:00 burton1982 notifications@github.com:

**Comment by ghost** [comment]
hero ;-)

The Problem was that I had named something with an "ü"

Thanks!
