### ISSUE TITLE
No Permission

### ISSUE THREAD

**Issue by Jenbalco** [sardoj/VTModuleDesigner#2]
Hi there,

Thanks for a great extension.. Really the only thing  missing from the VT studio.

I have already attempted to create a couple different modules both from and already core modules but I keep running into this "Permission to perform the operation is denied for name" error message. Are you able to tell me: 
1 - Why that is and what the fix is or could be?
2 - I migrated from 5.4 to 6 - Could that be the reason and is a fresh install needed?
3 - Do you have some documentation or are looking for help in developing the documentation for this module.

Thanks,
JIM

**Comment by sardoj** [comment]
Hello,

Thank you very much for your feedback.
First of all, don't forget to create one and only one field as an identifier, checking the "Identifier" checkbox (in the field creation popup).
Then "Permission to perform the operation is denied for name" often appears when the module's name was not added (automatically) in the table "vtiger_ws_entity". Try to add the row manually.

For the moment, it is complicated to modify Vtiger Core modules, due to vtlib files (PackageImport, PackageExport, PackageUpdate). These files are not complete. I will try to share a patch to fix this bug.

I will make soon tutorials videos to explain how to use Module Designer....but it take time :-)

Regards,
Jonathan

**Comment by Jenbalco** [comment]
Thank you Jonathan! 

Great Tool you have added there indeed. I have since upgraded to the latest version and it works wonders with new module creation. Will look forward to your latest version for core module editing capabilities.

Thanks again!
Terrie
