### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by emz3emz** [sardoj/VTModuleDesigner#50]
once i made the new module and install it then going to its page i found this error !

Permission to perform the operation is denied for name

did i miss something

**Comment by playmono** [comment]
Hi, this is because through the installation some thing went wrong.

This error basically happens when there is no record at vtiger_ws_entity with the module id. (Insert in vtiger_ws_entity is the last step of module installation).

I recommend you debugging while installation and see what happened.

Anyway we should log and show the log after installation I think.
